# Generated by Django 3.0.5 on 2020-04-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/tire.png', upload_to='profile_pics'),
        ),
    ]
