# Generated by Django 3.0.5 on 2020-04-24 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('Image', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
