# Generated by Django 3.0.3 on 2020-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200425_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='images'),
        ),
    ]
