# Generated by Django 3.0.5 on 2020-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200427_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='miniature',
            field=models.ImageField(default=None, upload_to='', null=True,blank=True),
        ),
    ]
