# Generated by Django 3.0.5 on 2020-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_project_miniature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='miniature',
            field=models.ImageField(default=None, null=True, upload_to='', blank=True),
        ),
    ]
