# Generated by Django 3.0.5 on 2020-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200427_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='miniature',
            field=models.ImageField(default='profile_pics/default.png', upload_to='images'),
        ),
    ]
