# Generated by Django 3.0.5 on 2020-04-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_project_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description2',
        ),
    ]
