# Generated by Django 3.0.5 on 2020-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_project_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='miniature',
            field=models.ImageField(default='static/arduino.jpg', upload_to='images'),
        ),
    ]
