# Generated by Django 3.0.5 on 2020-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200510_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='miniature',
            field=models.ImageField(default='imgaes/arduino.jpg', upload_to='images/'),
        ),
    ]
